# Generated by Django 4.1.2 on 2022-10-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=250, unique=True, verbose_name='Модель автомобиля')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модель авто',
            },
        ),
        migrations.CreateModel(
            name='CarMarka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_marka', models.CharField(max_length=250, unique=True, verbose_name='Марка автомобиля')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='модели', to='autoriaadmin.carmodel', verbose_name='таблица моделей')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марка авто',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='Модель автомобиля из названия в авториа')),
                ('price', models.CharField(max_length=250, null=True, verbose_name='цена автомобиля')),
                ('currency', models.CharField(max_length=100, null=True, verbose_name='Валюта')),
                ('miles', models.CharField(max_length=250, null=True, verbose_name='пробег автомобиля')),
                ('phone', models.CharField(max_length=250, null=True, verbose_name='Номер телефона')),
                ('url', models.URLField(null=True, verbose_name='Ссылка на объявление')),
                ('public_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('car_info_marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='марки', to='autoriaadmin.carmarka', verbose_name='таблица марок авто')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
